// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSay9JwLWHQIKub5ouPToDza7f3Vopexk',
    appId: '1:229876538562:web:500ab0571ca3c2c6456f5b',
    messagingSenderId: '229876538562',
    projectId: 'canser-1e437',
    authDomain: 'canser-1e437.firebaseapp.com',
    storageBucket: 'canser-1e437.firebasestorage.app',
    measurementId: 'G-WEM7RX0T6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5crUutxzVcpK2iCIak0QDYxvm1iAB7V4',
    appId: '1:229876538562:android:a4637030f84e8471456f5b',
    messagingSenderId: '229876538562',
    projectId: 'canser-1e437',
    storageBucket: 'canser-1e437.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoXpDg-YkI-1E65LMXDokXFwd167WxQSQ',
    appId: '1:229876538562:ios:c75837ef4db24e0a456f5b',
    messagingSenderId: '229876538562',
    projectId: 'canser-1e437',
    storageBucket: 'canser-1e437.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoXpDg-YkI-1E65LMXDokXFwd167WxQSQ',
    appId: '1:229876538562:ios:378d73f55b10cdd6456f5b',
    messagingSenderId: '229876538562',
    projectId: 'canser-1e437',
    storageBucket: 'canser-1e437.firebasestorage.app',
    iosBundleId: 'com.example.firstApp.RunnerTests',
  );
}
